version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - cv_model_stringing

  cv_model_stringing:
    build: ./app/cv_models
    container_name: cv_model_stringing
    command: python stringing.py
    ports:
      - "5001:5001"
    volumes:
      - ./app/static/uploads:/uploads
      - ./models:/models:ro
    environment:
      - MODEL_PATH=/models/

