version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - cv_model_stringing
      - cv_model_layers
      - cv_model_alignment

  cv_model_stringing:
    build: ./app/cv_models
    container_name: cv_model_stringing
    command: python stringing.py
    ports:
      - "5001:5001"
    volumes:
      - ./app/static/uploads:/uploads
      - ./models/3dpqc_model.xml:/models/3dpqc_model.xml:ro
    environment:
      - MODEL_PATH=/models/3dpqc_model.xml

  cv_model_layers:
    build: ./app/cv_models
    container_name: cv_model_layers
    command: python layer_quality.py
    volumes:
      - ./app/static/uploads:/uploads

  cv_model_alignment:
    build: ./app/cv_models
    container_name: cv_model_alignment
    command: python alignment.py
    volumes:
      - ./app/static/uploads:/uploads
